version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: alohomora
      POSTGRES_DB: nest
    networks:
      - nestnetwork
    restart: always
networks:
  nestnetwork:
